# Generated by Django 4.2.25 on 2025-12-20 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="bill_no",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="credit_amount",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="delivery_date",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="follow_up_date",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="free_service",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="is_accident",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="job_done_on_vehicle",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="labour_charge",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="paid_service",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="post_service_feedback_date",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="remarks",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="repair_job",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="repeat_job",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="warranty_job",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="address",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="email",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="name",
        ),
        migrations.RemoveField(
            model_name="technician",
            name="address",
        ),
        migrations.RemoveField(
            model_name="technician",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="technician",
            name="email",
        ),
        migrations.RemoveField(
            model_name="technician",
            name="name",
        ),
        migrations.AddField(
            model_name="purchase",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="handled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="designation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="user",
            field=models.OneToOneField(
                blank=True,
                limit_choices_to={"role": "staff"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="technician",
            name="specialization",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="technician",
            name="user",
            field=models.OneToOneField(
                blank=True,
                limit_choices_to={"role": "technician"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="total_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("staff", "Staff"),
                    ("technician", "Technician"),
                ],
                default="staff",
                max_length=20,
            ),
        ),
    ]
