# Generated by Django 4.2.25 on 2025-12-21 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="is_paid",
        ),
        migrations.AddField(
            model_name="sale",
            name="is_paid_status",
            field=models.CharField(
                choices=[
                    ("not_paid", "Not Paid"),
                    ("partial", "Partially Paid"),
                    ("paid", "Paid"),
                ],
                default="not_paid",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="labour_charge",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="sale",
            name="handled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="paid_from",
            field=models.CharField(
                blank=True,
                choices=[("cash", "Cash"), ("esewa", "eSewa"), ("both", "Both")],
                max_length=20,
                null=True,
            ),
        ),
    ]
