# Generated by Django 4.2.25 on 2025-12-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_sale_bill_no_remove_sale_credit_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseitem",
            name="sale_price",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="purchaseitem",
            name="vat",
            field=models.FloatField(default=13),
        ),
        migrations.AddField(
            model_name="sale",
            name="km_driven",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="stock",
            name="group",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
