# Generated by Django 4.2.25 on 2025-12-21 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_sale_is_paid_sale_is_paid_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sale",
            old_name="is_paid_status",
            new_name="is_paid",
        ),
    ]
