# Generated by Django 4.2.25 on 2025-12-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_purchaseitem_sale_price_purchaseitem_vat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseitem",
            name="vat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="vat",
            field=models.FloatField(default=0),
        ),
    ]
