# Generated by Django 4.2.25 on 2025-12-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_is_paid_status_sale_is_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="paid_amount",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
