# Generated by Django 4.2.25 on 2025-12-20 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_purchaseitem_vat_alter_stock_vat"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="stock",
            name="unique_item_per_category",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="discount_amount",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="net_amount",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="vat_amount",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_admin",
        ),
        migrations.AddField(
            model_name="followupdashboard",
            name="expected_km",
            field=models.IntegerField(
                default=1500, help_text="KM at which follow-up is required"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="followupdashboard",
            name="delivery_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="followupdashboard",
            name="follow_up_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="followupdashboard",
            name="sale",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followup",
                to="core.sale",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="user",
            field=models.OneToOneField(
                limit_choices_to={"role": "staff"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="technician",
            name="user",
            field=models.OneToOneField(
                limit_choices_to={"role": "technician"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="technician_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stock",
            unique_together={("name", "model", "category")},
        ),
    ]
