# Generated by Django 4.2.25 on 2025-12-21 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_sale_paid_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="advance",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="labour_charge",
        ),
    ]
