# Generated by Django 4.2.25 on 2025-12-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_stock_unique_item_per_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="remaining_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="total_amount",
            field=models.FloatField(default=0),
        ),
    ]
