# Generated by Django 4.2.25 on 2025-12-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_sale_advance_remove_sale_labour_charge"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="labour_charge",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
