# Generated by Django 4.2.25 on 2025-12-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_sale_labour_charge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
