# Generated by Django 4.2.25 on 2025-12-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_sale_is_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="is_paid",
            field=models.TextField(blank=True, null=True),
        ),
    ]
