# Generated by Django 4.2.25 on 2025-12-22 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_sale_is_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followupdashboard",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="followupdashboard",
            name="delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="followupdashboard",
            name="expected_km",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="followupdashboard",
            name="follow_up_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="followupdashboard",
            name="sale",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="core.sale"
            ),
        ),
    ]
