# Generated by Django 4.2.25 on 2025-12-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_followupdashboard_assigned_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="followupdashboard",
            name="post_service_feedback_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
