# Generated by Django 4.2.25 on 2025-12-22 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_followupdashboard_post_service_feedback_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="followupdashboard",
            name="expected_km",
        ),
        migrations.AddField(
            model_name="followupdashboard",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="followupdashboard",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("terminated", "Terminated"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="followupdashboard",
            name="terminated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
