# Generated by Django 4.2.25 on 2025-12-22 07:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_followupdashboard_expected_km_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="followupdashboard",
            name="termination_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="followupdashboard",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
