# Generated by Django 4.2.25 on 2025-12-22 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_followupdashboard_termination_reason_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="followupdashboard",
            old_name="termination_reason",
            new_name="reason",
        ),
    ]
