# Generated by Django 4.2.25 on 2025-12-22 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_rename_termination_reason_followupdashboard_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[("daily", "Daily"), ("monthly", "Monthly")],
                        max_length=10,
                    ),
                ),
                ("salary_date", models.DateField(blank=True, null=True)),
                ("month", models.PositiveIntegerField(blank=True, null=True)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("base_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "adjustment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("partial", "Partially Paid"),
                            ("paid", "Paid"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salaries",
                        to="core.staff",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffSalaryConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salary_type",
                    models.CharField(
                        choices=[("daily", "Daily"), ("monthly", "Monthly")],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "staff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_config",
                        to="core.staff",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalaryPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("cash", "Cash"), ("online", "Online")], max_length=10
                    ),
                ),
                ("payment_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "salary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="core.salary",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="salary",
            constraint=models.UniqueConstraint(
                condition=models.Q(("period_type", "daily")),
                fields=("staff", "salary_date"),
                name="unique_daily_salary",
            ),
        ),
        migrations.AddConstraint(
            model_name="salary",
            constraint=models.UniqueConstraint(
                condition=models.Q(("period_type", "monthly")),
                fields=("staff", "month", "year"),
                name="unique_monthly_salary",
            ),
        ),
    ]
