# Generated by Django 4.2.25 on 2025-12-22 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_salary_staffsalaryconfig_salarypayment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("total_salary", models.FloatField()),
                ("paid_amount", models.FloatField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("partial", "Partial"),
                            ("paid", "Paid"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        blank=True,
                        choices=[("cash", "Cash"), ("online", "Online")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.staff",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="salarypayment",
            name="received_by",
        ),
        migrations.RemoveField(
            model_name="salarypayment",
            name="salary",
        ),
        migrations.RemoveField(
            model_name="staffsalaryconfig",
            name="staff",
        ),
        migrations.DeleteModel(
            name="Salary",
        ),
        migrations.DeleteModel(
            name="SalaryPayment",
        ),
        migrations.DeleteModel(
            name="StaffSalaryConfig",
        ),
    ]
