# Generated by Django 4.2.25 on 2025-12-23 15:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_salarytracker_remove_salarypayment_received_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="salary_mode",
            field=models.CharField(
                choices=[("direct", "Direct Payment"), ("salary", "Salary Based")],
                default="direct",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="SalaryTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("payment", "Payment"),
                            ("advance", "Advance"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=15,
                    ),
                ),
                ("amount", models.FloatField()),
                ("payment_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "payment_mode",
                    models.CharField(
                        blank=True,
                        choices=[("cash", "Cash"), ("online", "Online")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "salary_tracker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="core.salarytracker",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_transactions",
                        to="core.staff",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "expense_type",
                    models.CharField(
                        choices=[("operational", "Operational"), ("other", "Other")],
                        max_length=20,
                    ),
                ),
                ("amount", models.FloatField()),
                ("expense_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[("cash", "Cash"), ("online", "Online")], max_length=10
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("reference_id", models.PositiveIntegerField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "spent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="core.staff",
                    ),
                ),
            ],
        ),
    ]
