# Generated by Django 4.2.25 on 2025-12-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_staff_salary_mode_salarytransaction_expense"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salarytransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("payment", "Purchase payment"),
                    ("advance", "Advance"),
                    ("salary", "Salary"),
                    ("operational", "operational"),
                    ("saving", "Saving"),
                    ("others", "Others"),
                ],
                max_length=20,
            ),
        ),
    ]
