# Generated by Django 4.2.25 on 2025-12-23 18:43

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_salarytransaction_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="expense_date",
            field=models.DateField(default=core.models.today_date, null=True),
        ),
        migrations.AlterField(
            model_name="sale",
            name="is_paid",
            field=models.CharField(
                blank=True,
                choices=[
                    ("not_paid", "Not Paid"),
                    ("partial", "Partially Paid"),
                    ("paid", "Paid"),
                ],
                default="not_paid",
                max_length=20,
            ),
        ),
    ]
