# Generated by Django 4.2.25 on 2025-12-24 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_expense_expense_date_alter_sale_is_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followupdashboard",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.staff",
            ),
        ),
    ]
