# Generated by Django 4.2.25 on 2025-12-24 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_followupdashboard_assigned_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followupdashboard",
            name="sale",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.sale",
            ),
        ),
    ]
