# Generated by Django 4.2.25 on 2025-12-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_followupdashboard_sale"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="is_migrated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sale",
            name="is_migrated",
            field=models.BooleanField(default=False),
        ),
    ]
