# Generated by Django 4.2.25 on 2025-12-24 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_purchase_is_migrated_sale_is_migrated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="handled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.staff",
            ),
        ),
    ]
