# Generated by Django 4.2.25 on 2025-12-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alter_sale_handled_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="expense_type",
            field=models.CharField(
                choices=[
                    ("salary", "Salary"),
                    ("operational", "Operational"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
