# Generated by Django 4.2.25 on 2025-12-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_expense_expense_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseitem",
            name="vat",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
