# Generated by Django 4.2.25 on 2025-12-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_alter_purchaseitem_vat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="is_paid",
            field=models.CharField(
                choices=[
                    ("not_paid", "Not Paid"),
                    ("partial", "Partial"),
                    ("paid", "Paid"),
                ],
                default="not_paid",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="km_driven",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sale",
            name="labour_charge",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="sale",
            name="paid_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="sale",
            name="paid_from",
            field=models.CharField(
                blank=True,
                choices=[("cash", "Cash"), ("online", "Online"), ("both", "Both")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="remaining_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="sale",
            name="total_amount",
            field=models.FloatField(default=0),
        ),
    ]
