# Generated by Django 4.2.25 on 2025-12-26 05:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_alter_sale_is_paid_alter_sale_km_driven_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="salarytracker",
            options={"ordering": ["-year", "-month"]},
        ),
        migrations.RemoveField(
            model_name="salarytransaction",
            name="salary_tracker",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="salary_mode",
        ),
        migrations.AddField(
            model_name="salarytracker",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="salarytracker",
            name="month",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salarytracker",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salarytransaction",
            name="tracker",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="core.salarytracker",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="staff",
            name="monthly_salary",
            field=models.FloatField(
                blank=True,
                help_text="Required only for monthly salary staff",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="salary_type",
            field=models.CharField(
                choices=[("daily", "Daily Payment"), ("monthly", "Monthly Salary")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="salarytracker",
            name="staff",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salary_trackers",
                to="core.staff",
            ),
        ),
        migrations.AlterField(
            model_name="salarytracker",
            name="total_salary",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="salarytransaction",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="salarytransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("salary", "Salary"),
                    ("advance", "Advance"),
                    ("bonus", "Bonus"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="salarytracker",
            unique_together={("staff", "year", "month")},
        ),
        migrations.CreateModel(
            name="SalaryAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.FloatField(help_text="Positive or negative adjustment"),
                ),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_adjustments",
                        to="core.staff",
                    ),
                ),
                (
                    "tracker",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="core.salarytracker",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="salarytracker",
            name="date",
        ),
        migrations.RemoveField(
            model_name="salarytracker",
            name="payment_mode",
        ),
    ]
