# Generated by Django 4.2.25 on 2025-12-26 06:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_salarytracker_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="salarytracker",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="salarytracker",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="salarytransaction",
            name="tracker",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="monthly_salary",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="salary_type",
        ),
        migrations.AddField(
            model_name="salarytracker",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="salarytracker",
            name="payment_mode",
            field=models.CharField(
                blank=True,
                choices=[("cash", "Cash"), ("online", "Online")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="salarytransaction",
            name="salary_tracker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="core.salarytracker",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="salary_mode",
            field=models.CharField(
                choices=[("direct", "Direct Payment"), ("salary", "Salary Based")],
                default="direct",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="salarytracker",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.staff",
            ),
        ),
        migrations.AlterField(
            model_name="salarytracker",
            name="total_salary",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="salarytransaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="salarytransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("payment", "Purchase payment"),
                    ("advance", "Advance"),
                    ("salary", "Salary"),
                    ("operational", "operational"),
                    ("saving", "Saving"),
                    ("others", "Others"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name="SalaryAdjustment",
        ),
        migrations.RemoveField(
            model_name="salarytracker",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="salarytracker",
            name="month",
        ),
        migrations.RemoveField(
            model_name="salarytracker",
            name="year",
        ),
    ]
