# Generated by Django 4.2.25 on 2025-12-26 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_alter_salarytracker_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salarytracker",
            name="date",
            field=models.DateField(default=datetime.date(2025, 12, 26)),
        ),
    ]
