# Generated by Django 4.2.25 on 2025-12-26 06:42

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_alter_salarytracker_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salarytracker",
            name="date",
            field=models.DateField(default=core.models.today_date),
        ),
    ]
