# Generated by Django 4.2.25 on 2025-12-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_alter_salarytracker_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salarytracker",
            name="total_salary",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="salarytransaction",
            name="payment_date",
            field=models.DateField(),
        ),
    ]
