# Generated by Django 4.2.25 on 2025-12-26 07:35

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_alter_salarytracker_total_salary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salarytransaction",
            name="created_at",
            field=models.DateField(default=core.models.today_date),
        ),
        migrations.AlterField(
            model_name="salarytransaction",
            name="payment_date",
            field=models.DateField(default=core.models.today_date),
        ),
    ]
