# Generated by Django 4.2.25 on 2025-12-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_alter_salarytransaction_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="salary_mode",
            field=models.CharField(
                choices=[("daily", "Daily Based"), ("salary", "Salary Based")],
                default="monthly",
                max_length=10,
            ),
        ),
    ]
