# Generated by Django 4.2.25 on 2025-12-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_alter_staff_salary_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="salary_mode",
            field=models.CharField(
                choices=[("daily", "Daily Based"), ("monthly", "Monthly Based")],
                default="monthly",
                max_length=10,
            ),
        ),
    ]
