# Generated by Django 4.2.25 on 2025-12-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_alter_staff_salary_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salarytransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("payment", "Purchase payment"),
                    ("advance", "Advance"),
                    ("daily_salary", "Daily Salary"),
                    ("monthly-salary", "Monthly Salary"),
                    ("operational", "operational"),
                    ("saving", "Saving"),
                    ("others", "Others"),
                ],
                max_length=20,
            ),
        ),
    ]
