# Generated by Django 4.2.25 on 2025-12-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_alter_salarytransaction_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salarytracker",
            name="note",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
