# Generated by Django 4.2.25 on 2026-01-01 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_alter_salarytracker_note"),
    ]

    operations = [
        migrations.RenameField(
            model_name="saleitem",
            old_name="price",
            new_name="total_price",
        ),
        migrations.AddField(
            model_name="saleitem",
            name="sale_price",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="vat",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.stock"
            ),
        ),
    ]
