# Generated by Django 4.2.25 on 2026-01-02 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_rename_price_saleitem_total_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saleitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.stock"
            ),
        ),
    ]
