# Generated by Django 4.2.25 on 2026-01-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_alter_saleitem_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchase",
            name="is_migrated",
        ),
        migrations.RemoveField(
            model_name="purchaseitem",
            name="vat",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="vat",
        ),
        migrations.AddField(
            model_name="purchase",
            name="discount_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="purchase",
            name="grand_total",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="purchase",
            name="net_total",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="purchase",
            name="paid_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="purchase",
            name="remaining_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="purchase",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("partial", "Partial"),
                    ("paid", "Paid"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="vat_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="vat_percentage",
            field=models.FloatField(default=0),
        ),
    ]
