# Generated by Django 4.2.25 on 2026-01-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_remove_purchase_is_migrated_remove_purchaseitem_vat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="is_migrated",
            field=models.BooleanField(default=False),
        ),
    ]
