# Generated by Django 4.2.25 on 2026-01-05 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_purchase_is_migrated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.staff",
            ),
        ),
    ]
