# Generated by Django 4.2.25 on 2026-01-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_alter_purchase_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="paid_from",
            field=models.CharField(
                choices=[("cash", "Cash"), ("online", "Online"), ("both", "Both")],
                default="cash",
                max_length=20,
            ),
        ),
    ]
