# Generated by Django 4.2.25 on 2026-01-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_purchase_paid_from"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sale",
            old_name="total_amount",
            new_name="discount_amount",
        ),
        migrations.AddField(
            model_name="sale",
            name="discount_percentage",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="sale",
            name="grand_total",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="sale",
            name="net_total",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="sale",
            name="vat_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="sale",
            name="vat_percentage",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="total_price",
            field=models.FloatField(default=0),
        ),
    ]
