# Generated by Django 4.2.25 on 2026-01-05 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_rename_total_amount_sale_discount_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="is_migrated",
        ),
    ]
