# Generated by Django 4.2.25 on 2026-01-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_remove_sale_is_migrated"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="is_migrated",
            field=models.BooleanField(default=False),
        ),
    ]
