# Generated by Django 4.2.25 on 2026-01-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_sale_is_migrated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saleitem",
            name="vat",
        ),
        migrations.AlterField(
            model_name="sale",
            name="paid_from",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
