# Generated by Django 4.2.25 on 2026-01-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_remove_saleitem_vat_alter_sale_paid_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="grand_total",
            field=models.FloatField(),
        ),
    ]
