# Generated by Django 4.2.25 on 2026-01-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_alter_sale_grand_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="grand_total",
            field=models.FloatField(default=0),
        ),
    ]
