# Generated by Django 4.2.25 on 2026-01-12 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_alter_sale_grand_total"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchase",
            name="vat_amount",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="vat_percentage",
        ),
    ]
