# Generated by Django 4.2.25 on 2026-01-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_remove_sale_vat_amount_remove_sale_vat_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="vehicle_type",
            field=models.CharField(
                blank=True,
                choices=[("bike", "Bike"), ("scooty", "Scooty"), ("other", "Other")],
                max_length=10,
                null=True,
            ),
        ),
    ]
