# Generated by Django 4.2.25 on 2026-01-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_sale_vehicle_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="vehicle_type",
            field=models.CharField(
                blank=True,
                choices=[("bike", "Bike"), ("scooty", "Scooty")],
                max_length=10,
                null=True,
            ),
        ),
    ]
