# Generated by Django 4.2.25 on 2026-01-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_alter_sale_vehicle_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="sale_ref",
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
