# Generated by Django 4.2.25 on 2026-01-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_sale_sale_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="block",
            field=models.CharField(
                blank=True,
                help_text="Stock location e.g. Block A / Godown 1 / Rack B2",
                max_length=100,
                null=True,
            ),
        ),
    ]
