# Generated by Django 4.2.25 on 2026-01-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_stock_block"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("received", "Received"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
