# Generated by Django 4.2.25 on 2026-01-25 10:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_order_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="BikeSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=150)),
                ("contact_no", models.CharField(max_length=20)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[("bike", "Bike"), ("scooty", "Scooty")], max_length=10
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("color", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "registration_no",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("chassis_no", models.CharField(max_length=100, unique=True)),
                ("engine_no", models.CharField(max_length=100, unique=True)),
                ("invoice_no", models.CharField(max_length=50, unique=True)),
                ("sale_date", models.DateField(default=django.utils.timezone.now)),
                ("sale_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BikeSalePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("full", "Full Paid"), ("installment", "Installment")],
                        max_length=15,
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "installment_tenure",
                    models.PositiveIntegerField(
                        blank=True, help_text="Number of months", null=True
                    ),
                ),
                (
                    "installment_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monthly installment amount",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sale",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="core.bikesale",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Installment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installment_no", models.PositiveIntegerField()),
                ("due_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_paid", models.BooleanField(default=False)),
                ("paid_date", models.DateField(blank=True, null=True)),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="core.bikesale",
                    ),
                ),
            ],
            options={
                "ordering": ["installment_no"],
                "unique_together": {("sale", "installment_no")},
            },
        ),
    ]
