# Generated by Django 4.2.25 on 2026-01-25 12:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_bikesale_bikesalepayment_installment"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="installment",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="installment",
            name="sale",
        ),
        migrations.RemoveField(
            model_name="bikesale",
            name="address",
        ),
        migrations.RemoveField(
            model_name="bikesale",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="bikesale",
            name="engine_no",
        ),
        migrations.AddField(
            model_name="bikesale",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="bikesale",
            name="handled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.staff",
            ),
        ),
        migrations.AddField(
            model_name="bikesale",
            name="is_paid_status",
            field=models.CharField(
                choices=[
                    ("not_paid", "Not Paid"),
                    ("partial", "Partial"),
                    ("paid", "Paid"),
                ],
                default="not_paid",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bikesale",
            name="is_servicing",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="bikesale",
            name="labour_charge",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="bikesale",
            name="paid_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="bikesale",
            name="paid_from",
            field=models.CharField(
                blank=True,
                choices=[("cash", "Cash"), ("online", "Online"), ("both", "Both")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bikesale",
            name="remaining_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="bikesale",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="bikesale",
            name="chassis_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="bikesale",
            name="color",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="bikesale",
            name="contact_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="bikesale",
            name="customer_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="bikesale",
            name="registration_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="bikesale",
            name="sale_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="bikesale",
            name="sale_price",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="bikesale",
            name="vehicle_type",
            field=models.CharField(
                blank=True,
                choices=[("bike", "Bike"), ("scooty", "Scooty"), ("other", "Other")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="BikeSalePayment",
        ),
        migrations.DeleteModel(
            name="Installment",
        ),
    ]
