# Generated by Django 4.2.25 on 2026-01-25 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_alter_installment_unique_together_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BikeSale",
        ),
    ]
