# Generated by Django 4.2.25 on 2026-01-25 14:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_delete_bikesale"),
    ]

    operations = [
        migrations.CreateModel(
            name="BikeSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=200)),
                ("contact_no", models.CharField(max_length=15)),
                ("address", models.TextField(blank=True, null=True)),
                ("bike_brand", models.CharField(max_length=100)),
                ("bike_model", models.CharField(max_length=100)),
                ("registration_no", models.CharField(max_length=50, unique=True)),
                ("chassis_no", models.CharField(max_length=50, unique=True)),
                ("engine_no", models.CharField(max_length=50, unique=True)),
                ("color", models.CharField(blank=True, max_length=50, null=True)),
                ("km_driven", models.FloatField(default=0)),
                (
                    "sale_type",
                    models.CharField(
                        choices=[
                            ("full", "Full Payment"),
                            ("downpayment", "Downpayment"),
                            ("emi", "EMI"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sale_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("total_amount", models.FloatField()),
                ("discount", models.FloatField(default=0)),
                ("net_total", models.FloatField()),
                ("paid_amount", models.FloatField(default=0)),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                            ("online", "Online"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("status", models.CharField(default="Pending", max_length=50)),
                ("remarks", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmiTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installment_no", models.PositiveIntegerField()),
                ("due_date", models.DateField()),
                ("amount_due", models.FloatField()),
                ("paid_amount", models.FloatField(default=0)),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(default="Pending", max_length=20)),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emi_details",
                        to="core.bikesale",
                    ),
                ),
            ],
            options={
                "ordering": ["installment_no"],
                "unique_together": {("sale", "installment_no")},
            },
        ),
    ]
