# Generated by Django 4.2.25 on 2026-01-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_bikesale_emitracker"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bikesale",
            old_name="bike_brand",
            new_name="vehicle_model",
        ),
        migrations.RemoveField(
            model_name="bikesale",
            name="bike_model",
        ),
        migrations.AddField(
            model_name="bikesale",
            name="vehicle_type",
            field=models.CharField(
                choices=[("bike", "Bike"), ("scooty", "Scooty")],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
