# Generated by Django 4.2.25 on 2026-01-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_rename_bike_brand_bikesale_vehicle_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bikesale",
            name="emi_amount",
            field=models.FloatField(
                blank=True, help_text="Calculated EMI per month", null=True
            ),
        ),
        migrations.AddField(
            model_name="bikesale",
            name="emi_tenure",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of EMI months", null=True
            ),
        ),
    ]
