# Generated by Django 4.2.25 on 2026-01-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_bikesale_emi_amount_bikesale_emi_tenure"),
    ]

    operations = [
        migrations.AddField(
            model_name="bikesale",
            name="remaining_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="bikesale",
            name="emi_amount",
            field=models.FloatField(blank=True, help_text="EMI per month", null=True),
        ),
        migrations.AlterField(
            model_name="bikesale",
            name="emi_tenure",
            field=models.PositiveIntegerField(
                blank=True, help_text="EMI tenure in months", null=True
            ),
        ),
    ]
