# Generated by Django 4.2.25 on 2026-01-25 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_bikesale_remaining_amount_alter_bikesale_emi_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bikesale",
            name="emi_amount",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bikesale",
            name="emi_tenure",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bikesale",
            name="sale_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="bikesale",
            name="status",
            field=models.CharField(max_length=50),
        ),
    ]
