# Generated by Django 4.2.25 on 2026-01-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_alter_bikesale_emi_amount_alter_bikesale_emi_tenure_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emitracker",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("cash", "Cash"), ("cheque", "Cheque"), ("online", "Online")],
                max_length=20,
                null=True,
            ),
        ),
    ]
