# Generated by Django 4.2.25 on 2026-01-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0064_emitracker_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="bikesale",
            name="initial_paid_amount",
            field=models.FloatField(default=0),
        ),
    ]
