# Generated by Django 4.2.25 on 2026-01-26 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0065_bikesale_initial_paid_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="BikeSaleFollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=255)),
                ("contact_no", models.CharField(max_length=50)),
                ("vehicle", models.CharField(max_length=255)),
                ("delivery_date", models.DateField()),
                ("post_service_feedback_date", models.DateField()),
                ("follow_up_date", models.DateField()),
                ("remarks", models.TextField(blank=True, null=True)),
                ("status", models.CharField(default="pending", max_length=50)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bike_sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.bikesale"
                    ),
                ),
            ],
        ),
    ]
