# Generated by Django 4.2.25 on 2026-01-26 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_bikesalefollowup"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bikesalefollowup",
            name="assigned_to",
        ),
    ]
