# Generated by Django 4.2.25 on 2026-01-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_remove_bikesalefollowup_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="is_migrated",
            field=models.BooleanField(default=False),
        ),
    ]
