# Generated by Django 4.2.25 on 2026-01-29 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0068_stock_is_migrated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bikesale",
            name="initial_paid_amount",
        ),
    ]
