# Generated by Django 4.2.25 on 2026-01-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0069_remove_bikesale_initial_paid_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="bikesale",
            name="initial_paid_amount",
            field=models.FloatField(default=0),
        ),
    ]
