# Generated by Django 4.2.25 on 2026-02-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_bikesale_initial_paid_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='paid_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='remaining_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(
                max_length=10,
                choices=[('pending','Pending'),('partial','Partial'),('paid','Paid')],
                default='pending'
            ),
        ),
    ]
