# Generated by Django 4.2.25 on 2026-04-04 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_auto_20260216_2204"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stock",
            unique_together=set(),
        ),
    ]
