# Generated by Django 4.2.25 on 2026-04-04 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0072_alter_stock_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),  # removes the (name, model, category_id) constraint
        ),
]