# Generated by Django 4.2.25 on 2026-04-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0073_alter_stock_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="paid_amount",
            field=models.FloatField(default=0, null=True),
        ),
    ]
