# Generated by Django 4.2.30 on 2026-07-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0073_alter_stock_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="amount_before_transit_discount",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="purchase",
            name="transit_discount_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="purchase",
            name="transit_discount_percentage",
            field=models.FloatField(default=0),
        ),
    ]
