# Generated by Django 4.2.25 on 2026-04-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0074_alter_purchase_paid_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="paid_amount",
            field=models.FloatField(default=0),
        ),
    ]
