# Generated by Django 4.2.25 on 2026-04-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0075_alter_purchase_paid_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="after_discount_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="purchase",
            name="vat_amount",
            field=models.FloatField(default=0),
        ),
    ]
