# Generated by Django 4.2.30 on 2026-07-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0075_purchasereturn_salereturn_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleitem",
            name="return_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="returned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
