# Generated by Django 4.2.30 on 2026-07-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0076_saleitem_return_reason_saleitem_returned_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="is_fitting_job",
            field=models.BooleanField(default=False),
        ),
    ]
