# Generated by Django 4.2.30 on 2026-05-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0076_purchase_after_discount_amount_purchase_vat_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="bill_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
