# Generated by Django 4.2.30 on 2026-07-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0077_sale_is_fitting_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseitem",
            name="return_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseitem",
            name="returned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
