# Generated by Django 4.2.30 on 2026-05-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0077_purchase_bill_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="is_fitting",
            field=models.BooleanField(default=False),
        ),
    ]
