# Generated by Django 4.2.30 on 2026-08-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0078_purchaseitem_return_reason_purchaseitem_returned_at"),
    ]

    operations = [
      
        migrations.AddField(
            model_name="purchasereturn",
            name="bill_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
