# Generated by Django 4.2.30 on 2026-05-28 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0078_sale_is_fitting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followupdashboard",
            name="sale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.sale",
            ),
        ),
    ]
