# Generated by Django 4.2.30 on 2026-05-28 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0079_alter_followupdashboard_sale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saleitem",
            name="sale",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="core.sale",
            ),
        ),
    ]
