# Generated by Django 4.2.30 on 2026-05-28 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0080_alter_saleitem_sale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saleitem",
            name="sale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="core.sale",
            ),
        ),
    ]
