# Generated by Django 4.2.30 on 2026-08-12 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0079_purchase_bill_no_purchasereturn_bill_no"),
        ("core", "0081_alter_saleitem_sale"),
    ]

    operations = []
