# Generated by Django 4.2.30 on 2026-08-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0082_merge_20260812_1712"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="vat_percentage",
            field=models.FloatField(default=13),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="bill_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
